### ISSUE TITLE
Lock 10.22.0 breaks logins that don't redirect to Auth0's site?

### ISSUE THREAD

**Issue by Otoris** [auth0/lock#1128]
My team is currently in the process of building a SPA with React + Auth0 Lock. Updated our project to Lock 10.22.0 this morning in passing and have found minimal migration information. This update completely broke our login flow on all of our development builds.

I've spent the better part of the day learning what changes were needed, but it appears we're being forced into using a redirect to Auth0's site if we're embedding Lock? This is counterintuitive to our UX in our app, as we don't want the user seeing that they get redirected to Auth0 which is an unknown entity to them. This also gives a undesirable page reload/redirect that takes users out of our app. Is there anyway to re-enable the smooth SPA Lock login flow from the previous version without staying back on 10.21.1 and possibly missing security updates in the future? 

Lock Config:
```
    this.lock = new Auth0Lock(AUTH_CONFIG.clientId, AUTH_CONFIG.domain, {
      oidcConformant: true,
      container: 'loginContainer',
      allowSignUp: false,
      theme: {
        primaryColor: '#3BA8D7',
        logo: 'images/logo.png'
      },
      languageDictionary: {
        title: "TBA"
      },
      auth: {
        redirect: false,
        responseType: 'token id_token',
        audience: `https://${AUTH_CONFIG.domain}/userinfo`,
        params: {
          scope: 'openid'
        }
      }
    });
```
**We're aiming at keeping everything asynchronous, but don't know what is required to achieve that with the latest version since we continually get "Cross origin login is not supported in popup mode" in our localhost test environments.**

Lock Version: 10.22.0
Browser: Google Chrome Version 63.0.3218.0 (Official Build) dev (64-bit)

**Comment by luisrudge** [comment]
The 10.22.0 version is the first release that we actually support the `oidcConformant` flag, that's why you didn't see any migration guide for this version. We have docs specifically written about OIDC and Cross Origin Authentication and we added them to the [readme](https://github.com/auth0/lock#oidc-conformant-mode). We forgot to mention that popup mode won't be supported and I'll open a PR to add that info to the readme. In any case, here's our official recommendation:

- You should use the Hosted Login Page whenever possible.
- If you don't want to use the Hosted Login Page and also want to use the popup mode, then you have to set the `oidcConformant` flag to false in your lock configuration and also disable that in the dashboard.
- If you want to use the `oidcConformant` flag set to true, you'll have to follow our guidance [here](https://auth0.com/docs/cross-origin-authentication) on how to enable Cross Origin Authentication for your client. Keep in mind that this flow will do a redirect to Auth0's server in order to authenticate the user
