### ISSUE TITLE
Cannot change signupTitle

### ISSUE THREAD

**Issue by thameera** [auth0/lock#1173]
Changing the `signupTitle` in the dictionary object doesn't seem to have any effect. Currently it's not possible to change the Lock title when switching between the Log In and Sign Up tabs.

However, we have it [in the dictionary](https://github.com/auth0/lock/blob/d1b1ecb85efa6641122e46b493c52e39f3ae2f5c/src/i18n/en.js#L101).

Lock version: 10.21.1
Browser & OS: Chrome 62, macOS 10.13.1 (reproduced in any browser/OS)

Example code snippet:

```javascript
var lock = new Auth0Lock(CLIENT_ID, DOMAIN, {
  auth: {
    redirectUrl: 'https://example.com',
    responseType: 'token id_token',
    params: {
      scope: 'openid profile'
    },
  },
  languageDictionary: {
    signupTitle: 'this label not shown anywhere'
  }
});
```

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!

**Comment by 7rakir** [comment]
The issue is still there in v10, but in v11 it seems to be fixed. I'll keep it closed seeing v10 will be deprecated as of April 1, 2018.

I must say that I find it surprising that the issue (arguably created by someone from Auth0) didn't get any attention for almost four months and when it did the first step was to automatically close it.

**Comment by luisrudge** [comment]
I was fairly confident that this specific issue was fixed in https://github.com/auth0/lock/pull/1288. Because of v10 deprecation and the new major release of v11, we had some tough decisions to make, one of them to leave low impact issues for later while we fixed mission critical ones. In this process we ended up fixing a lot of small issues as well, so I closed everything that appeared to either have been fixed or not be an issue anymore, hoping that we have a clearer issue list to work on. Sorry we took so long to fix this specific issue, but I'm glad it's fixed 🎉

**Comment by 7rakir** [comment]
I completely get the triage process and there's no need to apologize. Though at first it may have seemed like a go-to solution merely testing the reporter's attention whether they can notice the closing of the issue or not, it's clear this was not the case.

Thank you for fixing the issue. :)
