### ISSUE TITLE
Connection Resolver Fails with > 50 Connections

### ISSUE THREAD

**Issue by GavinOsborn** [auth0/lock#1194]
Hey guys,

When the connection resolver feature was released it could support Auth0 tenants with as many database connections as they like. This is important for us as we have > 3000 database connections and growing daily.

Subsequent releases of the lock widget have broken this feature such that it is limited to the connection list returned by the `https://cdn.auth0.com/client/<client-id>` endpoint - which as you know is limited to the first 50 connections.

Some observations from our dev team:

We are using lock v10.24.1 (the latest stable version we could find):
It can be observed that it performs connection resolution but *does not* appear to honor the connection passed through the callback if it is outside of the 50 connections. Instead it uses the default connection.
 
The lock in your [multi-tenant sample](https://github.com/auth0-samples/multi-tenant-db-per-tenant-lock) is v10.20:
This *does* honor the connection passed through the callback.

Our _suspicion_ is that this was caused by PR #1113 to address password manager support (#1081).
This moved the connectionResolver execution from onBlur to onSubmit.

Unfortunately we cannot adopt this feature until both password managers are supported and the connection limit is lifted.

Please advise :-)

**Comment by luisrudge** [comment]
We need to use one of the connections that we get in the client config file because we need more information about the connection (type etc), so you can't just resolve to a connection name. I know it's not ideal, but the real issue here is the 50 connections limit that we have no control over. I'd suggest you to share your feedback in https://auth0.com/feedback so our product team can prioritize the fix. Thanks!
