### ISSUE TITLE
Why do distribution files contain references to "/home/ubuntu/.strider/data"?

### ISSUE THREAD

**Issue by gjungb** [auth0/lock#128]
When running ```bower install auth0-lock``` the downloaded files ```auth0-lock.js``` and ```auth0-lock.min.js``` contain references to ```/home/ubuntu/.strider/data/auth0-lock-54e4dcdcbe8382d10c000657```.
This is strange, especially because ```grunt build``` on a fork of this repo produces references like ```/Users/gerd/WebstormProjects/lock/```.
Is there any reason to have hard coded pathes in the distribution files?

**Comment by pose** [comment]
Hi @gjungb,

You are right. It does not look nice.

It's possible those absolute paths are generated in the source map creation process. I agree they should be relative but you shouldn't get any error from that. Feel free to re-open if those paths are making your app or Lock instance fail.

Thanks,

**Comment by mohislm** [comment]
I'm also getting serious issue because of this. It's dumping all those urls in the JS file:
/home/ubuntu/.strider/data/auth0-lock-56b3b5696bc94eaa63cbfca7/standalone.js

FYI: I'm using gulp, bower, browser-sync build system. When I run my angular app locally it reference from individual file (using <script> tags). But when I concatenate all JS files and create a single vendor.js, then the issue occurs. I debugged thru the code and found out that these browserified resources are causing the issue.

**Comment by gnandretta** [comment]
@mohislm hi, what issue are you having?

**Comment by mohislm** [comment]
First of all, for God's sake please **OPEN** this issue. It still says: "Closed"!!!

The issue is most likely because you're using browserify for `auth0-lock` and `auth0-angular`. So when in my dev environment (localhost) I'm loading all the dependencies (i.e. these two modules) with separate script tags, everything is cool. However, when I concatenate these two with other modules/files (i.e. angular, angular-cookies etc.) the browser complains that some of the modules are unable to load.

So as a quick-fix I had to place these two modules at the very bottom of the bower.json, so that they get concatenated at the very end of the `vendor.js` file. If I place them in the middle, the browser throws an error saying could not load modules. **These two and anything that goes after them couldn't load**. FYI, I've notice that some scripts get loaded asynchronously via AMD by these two scripts.

I don't know the mechanism that you guys used for these two. I think if you use the following `bower.json` file you should be able to drill down to the issue. I'll be more than happy to provide more information if needed. Notice that I placed the two modules at the very end. Try to move them upwards and see what happens. If you were able/unable to replicate the issue, I'd appreciate if you leave a note here for me.

Thanks!

```
{
  "name": "myapp",
  "dependencies": {
    "angular": "~1.4.8",
    "angular-touch": "~1.4.8",
    "angular-ui-router": "~0.2.17",
    "angular-cookies": "~1.4.8",
    "a0-angular-storage": "~0.0.13",
    "angular-jwt": "~0.0.9",
    "auth0-lock": "~8.2.3",
    "auth0-angular": "~4.1.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.8"
  }
}
```
