### ISSUE TITLE
Safari login broken (scope params not working)

### ISSUE THREAD

**Issue by dcworldwide** [auth0/lock#1326]
Safari 11
Lock 11

Was working until upgraded to lock 11. I've lost customers and received bad app reviews. It's frustrating as a paid customer. 

```
this.lock = new Auth0Lock(this.config.auth.clientId, this.config.auth.domain, {
                    closable: args.closable == undefined ? true : args.closable,
                    allowSignUp: false,
                    theme: {
                        // logo: `${this.config.webUrl}/assets/logo.svg`,
                        logo: '',
                        primaryColor: '#1EBDB2',
                    },
                    languageDictionary: {
                        title: "Account login"
                    },
                    auth: {
                        params: {
                            scope: 'openid type status stores',
                            state: JSON.stringify({ redirect: args.redirect })
                        },
                        redirect: true,
                        redirectUrl: this.config.webUrl,
                        responseType: "token",
                    }
                })
```

Notes:

- I'm using lock 11 in react with the above code. 
- Issue is that stores status and type are not returned by  `scope: 'openid type status stores'`

I'm using the following rule to hoist the scope props into the user object on auth.

```
// This code is run on every auth request 
// User properties are not persisted. You need to use app_metadata to persist state.
// User properties are set so that the auth0 auth scope can access those values
function (user, context, callback) {
  user.app_metadata = user.app_metadata || {};
  
  // Array of stores the user is a member of. 
  user.stores = [];
 
  if (user.app_metadata.stores) {
    user.stores = user.app_metadata.stores.map(function(x) {
      return {
         sId: x.sId, 
         aId: x.aId
      }; 
    });
  }  
  
  // User type and status
  user.type = user.app_metadata.type;
  user.status = user.app_metadata.status;
 
  callback(null, user, context);
}
```

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by dcworldwide** [comment]
Explain this. It works for a year. I upgrade. It doesn't work.

**Comment by luisrudge** [comment]
Are you using the universal login page?

**Comment by dcworldwide** [comment]
Nope, auth0 lock latest, with a cross domain fallback.

**Comment by luisrudge** [comment]
Did you change your client type from non-oidc to oidc?

**Comment by luisrudge** [comment]
I reproduced your scenario and here are the results:

**User**
![image](https://user-images.githubusercontent.com/941075/38168589-fc37eb04-3526-11e8-9302-8f8b99a8d532.png)

- If my client is set to OIDC Conformant = `false`, then your script works just fine and I get all the custom fields by default
- If my client is set to OIDC Conformant = `true`, then your script doesn't work, because that's not how OIDC conformant clients work. More information about [OIDC clients here](https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant) and about [custom scope claims with OIDC clients here](https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims).

With my client set to OIDC Conformant = `true`, here's what your should look like in order to get the same result:

```js
// This code is run on every auth request 
// User properties are not persisted. You need to use app_metadata to persist state.
// User properties are set so that the auth0 auth scope can access those values
function (user, context, callback) {
  user.app_metadata = user.app_metadata || {};
  var stores = user.app_metadata.stores || [];
  
  var namespace = 'https://myapp.com/';
  context.idToken[namespace + 'stores'] = stores.map(function(x) {
    return {
      sId: x.sId, 
      aId: x.aId
    }; 
  });
  context.idToken[namespace + 'type'] = user.app_metadata.type;
  context.idToken[namespace + 'status'] = user.app_metadata.status;
  callback(null, user, context);
}
```

When I use this rule, the result of the `getUserInfo` method is:

![image](https://user-images.githubusercontent.com/941075/38168605-733b6bcc-3527-11e8-9c34-2adca754ad45.png)

If you have more questions, don't hesitate to contact our amazing support team at https://support.auth0.com

**Comment by dcworldwide** [comment]
Ok interesting, thankyou for taking the time to investigate. 

> Did you change your client type from non-oidc to oidc? 

We didn't make any changes

I can that the article says that OIDC compliance is a somewhat recent change. Any idea why our original code works in FF and Chrome but not Safari?

We had to find an immediately solution, so we decided to remove all auth0 code from our front end and have auth0 on the backend only. We didn't want to use the hosted page option or have to worry about auth0js upgrade refactoring.

**Comment by luisrudge** [comment]
OIDC clients are available for more than a year now. New clients are OIDC by default (I don't know the specific date that we started with this). I don't know if it's something specific to safari or not. That's why I said the support was the best way to figure it out. They'd ask you for a .HAR file and start the investigation. I'm glad it's working now!

**Comment by catamphetamine** [comment]
@dcworldwide Have you tries "custom domains" paid feature? Seems that it solves Safari bugs for people with the new Lock 11.

**Comment by dcworldwide** [comment]
We've decided that we've wasted too many maintenance hours with auth0 integration already ... so we decided not to invest more time in deeper integration I.e. hosted pages, custom domains and instead in a day we rolled our own solution... no cross domain issues, smaller bundle size, a more on brand ux. I only would recommend auth0 for when you are bootstrapping.

**Comment by catamphetamine** [comment]
@dcworldwide Well, yeah, basically, why I'm still doing some Auth0 is that it is a good bootstrapping solution, e.g. you're making a website for someone, or you're a freelancer, etc.
Still, making their own Lock authentication disfunctional without paid subscription devalues this approach in the aforementioned scenario. The universal login approach might work for free users but its setup is way too complicated one could pull off a smaller and better in-house solution like you did.
