### ISSUE TITLE
Let users switch language in lock

### ISSUE THREAD

**Issue by mbeckenbach** [auth0/lock#133]
There should be a button / dropdown to switch the language of lock at runtime. 

The selected language should could also be provided as a property in the user profile.
This would make it a lot easier to set up the user's preferred language in the app.

The available languages should be configurable by the developer.

**Comment by felixinx** [comment]
Maybe a `lock.show` option? This will be nice. I also recommand to use HTACESS to dertermine wich language user is using. This will be more user friendly for the frontend.

**Comment by cristiandouce** [comment]
I don't see how a dropdown inside the context of the lock's html would make any sense.

If you allow something like that, I'd rather see it at an Application level. Some dropdown on your appliaction which trigger.

As @felixinx says, you can use a pre-polulated language or pass your own dictionary:

- https://github.com/auth0/lock/wiki/Auth0Lock-customization#dict-stringobject
- https://github.com/auth0/lock/wiki/I18n

**Comment by mbeckenbach** [comment]
@felixinx Why not detect the browserlanguage in javascipt? I do that in all my multi language js apps. Works perfect.

**Comment by cristiandouce** [comment]
@mbeckenbach Wouldn't it look awkward if you enter a french site, and the lock triggers in japanese (or whatever your browser's locale is...)?

It's better that the lock matches the site's language, and for that it needs to be triggered from the site/application, IMHO

**Comment by mbeckenbach** [comment]
@cristiandouce No. It would not as long as the french site offers a japanese translation too. :-) 

Lots of sites do auto detect your language. Lock should have an option to enable it. It does not have to do it by default.

**Comment by mbeckenbach** [comment]
@cristiandouce This could also be awesome in registration as i know the users language before he starts using my app.

**Comment by cristiandouce** [comment]
That's my point.

If your site has an auto detect language, Lock does too:

```js
var browserLocal = getBrowserLocaleSetting();

lock.show({
  dict: browserLocale
});
```

If the site does not have a translation for the current browser locale, the Lock should not display in a different language as the site, therefore the default functionality should be to display with the language defined by the running site. The auto discover function here does not make sense, since the lock works withing an application/site context, and it should not dispair with it.

Besides, calling the `.show()` either with the `dict: discoveredLanguage` or `autoDiscoverLocale: true` is the same work.

I don't really see it as a useful feature at all, but most as a problem maker, since users may then disagree in how the Lock retrieves the locale from the browser as they do it differently for their application.

**Comment by waleedasad** [comment]
Hi @cristiandouce, 
How can we pass multiple languages? Iam using auth0 lock UI. My android app uses callback which opens a web view... how can we specify lock UI to change language based on Android app's language or whats the correct way to get Android clients language ?

**Comment by niksajanjic** [comment]
@waleedasad You can change language by passing `language` prop to configuration options:
https://auth0.com/docs/libraries/lock/v11/configuration#language-string-
