### ISSUE TITLE
Cannot switch SSO users

### ISSUE THREAD

**Issue by maxlapides** [auth0/lock#1332]
*Steps to reproduce:*
1. Log in with an SSO account (ex: me@mycompany.com)
2. Wait for token to expire or remove token from local storage
3. Attempt to log in as another SSO user (ex: friend@mycompany.com)
4. Automatically logs you into your original SSO account (ex: me@mycompany.com)

**Comment by luisrudge** [comment]
Are you seeing any errors etc?

**Comment by luisrudge** [comment]
No, just ruling out any SDK errors.  When you start step 3, the session is still active in the Authorization Server (Auth0), that's why you get logged in automatically. You'd have to [logout](https://auth0.com/docs/logout) first. This indeed doesn't look like a bug in the SDK itself. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario. They'll probably ask you your stack and a more detailed step-by-step, though, so keep that in mind. Thanks 🎉

**Comment by maxlapides** [comment]
@luisrudge I'm pretty certain this is a bug. This project comes with a button that says "Not your account?" and I would expect if I clicked that and entered a new email address, I would log in with that one and not the previous one. Can you please take a look at the `notYourAccountAction` button? I don't think this behavior is expected.

**Comment by luisrudge** [comment]
I 100% agree with you that this behavior is confusing. Unfortunately, all this project does is communicate with the authorization server. The "not your account" button does not log you out to end your session in Auth0's server, all it does is show the inputs again.
To be able to help, the support team needs a HAR file and check with the server team why that's happening.
