### ISSUE TITLE
resumeAuth error after upgrading from 11.3.0 to 11.5.2: `invalid token`

### ISSUE THREAD

**Issue by zachguo** [auth0/lock#1342]
- Lock v11.5.2 (I tested all versions from 11.3.0 to 11.5.2, this issue started since 11.5.0)
- Latest Chrome
- Error message for `resumeAuth`
```
{error: "invalid_token", errorDescription: "`state` does not match."}
```

My state config is something like following, it hasn't been changed for 2 years. Error happens only when state is not `/`.
```
{
      configurationBaseUrl: "https://cdn.auth0.com",
      ...
      auth: {
        ...
        params: {
          state: window.location.pathname + window.location.search,
          scope: "openid email app_metadata"
        }
      },
      ...
}
```

I'm using Lock in a SPA, a new `Auth0Lock` would be declared before every `lock.show()` to make sure `state: window.location.pathname + window.location.search` is up-to-date.
**Edit:**
I just found out `lock.show` can override options now, so I tried following. However, the same error persists.
```
// override state to make sure redirection url is up-to-date
    this.lock.show({
      auth: {
        params: {
          state: window.location.pathname + window.location.search
        }
      }
    });
```

**Comment by luisrudge** [comment]
can you paste the state that you receive in the hash and the state that you're using inside lock.show?

**Comment by zachguo** [comment]
a state passed to lock is `/deep/route`, in the hash that `resumeAuth` accepts is `state=%2Fdeep%2Froute`.

**Comment by luisrudge** [comment]
ok can you try using this state: `encodeURIComponent(
          state: window.location.pathname + window.location.search)`

**Comment by zachguo** [comment]
I can try it tomorrow, but TBH I don't think it is the cause, because it works when `state` is `/`.

**Comment by luisrudge** [comment]
Ok, let me know. If it doesn't work, please create a simple repro project so I can test this.

I can't see anything that changed the way we handle state checking in this release, so a repro project would help a lot.
https://github.com/auth0/lock/compare/v11.4.0...v11.5.0
https://github.com/auth0/auth0.js/compare/v9.3.3...v9.4.0

**Comment by luisrudge** [comment]
No, `opts` in this case is already whatever is inside the `auth` object: https://github.com/auth0/lock/blob/b970ab46da901ac4971a4b99aca7721018ba484b/src/core/actions.js#L29

**Comment by zachguo** [comment]
Not exactly sure how to create a reproducible repo. My complete Lock options are as following.
```js
    this.lock = new Auth0Lock(clientId, domain, {
      configurationBaseUrl: "https://cdn.auth0.com",
      allowSignUp: false,
      rememberLastLogin: false,
      closable: true,
      autoclose: true,
      avatar: null,
      theme: {
        primaryColor: "#2196f3"
      },
      auth: {
        redirect: true, // redirect mode is preferred to maximize browser compatibility
        redirectUrl: window.location.origin,
        responseType: "id_token token",
        params: {
          state: window.location.pathname + window.location.search,
          scope: "openid email app_metadata"
        }
      },
      mustAcceptTerms: true,
      languageDictionary
    });
```

**Comment by zachguo** [comment]
I just tried `state: encodeURIComponent(window.location.pathname + window.location.search)` with v11.5.0, error persists.

**Comment by luisrudge** [comment]
are you using angular? I just used your code and I don't get the encoded state:
![image](https://user-images.githubusercontent.com/941075/38739100-51861a62-3f0a-11e8-9abd-17c5368b5c24.png)

**Comment by zachguo** [comment]
I'm using React.
Encoded state is in the URL hash. `resumeAuth` throws error when passing `window.location.hash` to it.

**Comment by luisrudge** [comment]
I get that.. Here's what I'm seeing:

I get redirected to: `https://localhost:3000/support/#access_token=i4fsK3S9crMEbsugdzJ2c7kkWaDIEHE1&scope=openid%20profile%20email&expires_in=7200&token_type=Bearer&state=%2Fdeep%2Froute`, but my "hash_parsed" event emits the correct value:

![image](https://user-images.githubusercontent.com/941075/38757276-d1e4e91c-3f42-11e8-9258-57da37595faa.png)


This happens because the params get automatically decoded [here](https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L155)

Example: https://codesandbox.io/s/6wjj05r9xn

This is most likely an environment/code issue, so please create an isolated example of this example and, if you still see the error, let me know and I'll reopen the issue.

**Comment by luisrudge** [comment]
I created a codesandbox example with the same code you have:
[![Edit x0zpnzzq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x0zpnzzq)

keep in mind this example uses v15.5.2, from this link: https://cdn.auth0.com/js/lock/11.5.2/lock.min.js

**Comment by luisrudge** [comment]
Thanks for the sandbox. I now understand why it's failing. I thought it was some weird type of url encoding/decoding issue, but it's simpler than that:

This code runs from `https://k5lmwxmxv7.codesandbox.io/`, which will make `state` to be `/`
```js
var lock = new Auth0Lock('TnlRxGUgmqOYWt8pkZTlXcttyzRoLm7q', 'brucke.auth0.com', {
  auth: {
    redirectUrl: window.location.origin,
    params: {
      state: window.location.pathname + window.location.search
    }
  }
});
```

This code runs from `https://k5lmwxmxv7.codesandbox.io/deep/path `, which will make `state` to be `/deep/path `
```js
this.lock.show({
  auth: {
    params: {
      state: window.location.pathname + window.location.search
    }
  }
});
```

When you authenticate, you get redirected to `window.location.origin`, which is the first code block. Then, the `parseHash` method is called with the state that you're providing at that time, which is `/`.

This is happening because we fixed a bug in the way we loaded state [here](https://github.com/auth0/lock/commit/b427f5663706330708963eada292a3588ea4f80e#diff-c6a00993f478fa96cce27be2b801c923R37): 
![image](https://user-images.githubusercontent.com/941075/38883361-09288bec-4243-11e8-8bd7-29c0a13cf1c9.png)

Previously, the code was checking for state inside the `auth` object:

```js
this.lock.show({
  auth: {
    state: window.location.pathname + window.location.search
  }
});
```

This is a bug, because the correct and documented way of providing your own state is `auth.params`, like what you did.

The only reason it worked before is, because of this bug, the previous parseHash method was not using your `auth.params.state` to validate state. It was trying to use `auth.state`, which is undefined, causing the state validation to continue with the state provided in the url.

In your specific case, what you should do to make it work is remove the `state` assignement from the constructor call and leave it only in the `lock.show` method.

Working example: https://codesandbox.io/s/vvn9229vx7

Bottom of line is: if you want to send a state, you just have to set it in the `show` method. If you absolutely want to validate the hash with your own state, instead of relying on Lock's defaults, you have to make sure that all the `auth.params.state` match.
