### ISSUE TITLE
User email and password input fields do not display on Angular web app in Iphone IOS: 11.3

### ISSUE THREAD

**Issue by justinLaw** [auth0/lock#1362]
- Lock version - 11.6.0
- Browser & OS - iOS 11.3, Safari Only iPhones, not iPads.
- JavaScript framework: AngularJS 1.4.8
- also using angular-lock: 3.0.0
- Lock configuration:
```
   lockProvider.init ({
     domain: <domain>,
     clientID: <client id>,
     options: {
       _idTokenVerification: false,
       autoclose: true,
       configurationBaseUrl: 'https://cdn.auth0.com',
       auth: {
         responseType: "token",
         redirectUrl: <application index>,
         params: {
           scope: 'openid email id userId'
         }
       }
     }
   });
```
Calling lock.show () had the following login screen show.
![screen shot 2018-04-30 at 3 24 02 pm](https://user-images.githubusercontent.com/697437/39474403-73cc8e36-4d19-11e8-9db5-961c8919c217.png)

Toggling the "display: block !important" on and off in the dev tools causes the email and password fields to reappear.
<img width="994" alt="screen shot 2018-05-01 at 7 23 55 am" src="https://user-images.githubusercontent.com/697437/39474479-dbdd5294-4d19-11e8-867f-75cc750c9f59.png">

Turning the phone sideways causes the login page to display all fields when calling the lock.show () method. I have removed all of my sites custom css to ensure there were no problems with overriding styles. Have tested on earlier versions of IOS with no problems, it is only on IOS version 11.3. I'm assuming it has something to do with a media query for screen width but have not been able to verify this.

**Comment by luisrudge** [comment]
Did you test only on an iPhone X?

**Comment by justinLaw** [comment]
I have tested on Iphone 5s, 6, 6 plus, 6s, 6s Plus, 7, 7s, 7 plus, 8, 8 plus, and X.

**Comment by luisrudge** [comment]
All of them have the same issue? Do you have a public website I can test?

**Comment by justinLaw** [comment]
@luisrudge my manager said I could email you the url so sending one now.

**Comment by luisrudge** [comment]
Thanks @justinLaw I reproduced the issue on my iphone 6 and I'm also debugging this locally. The other report we had was also using angular (https://github.com/auth0/lock/issues/1357). I also tested this with the default sample with angular-lock (https://github.com/auth0-samples/auth0-angularjs-samples/tree/embedded-login/01-Embedded-Login) and I see the same issue. I think this is enough information to start investigating. I will move this issue to angular-lock, though, since this is an issue with that particular integration and not with lock itself.
