### ISSUE TITLE
Auth0Lock needs to reinitialise in order to invoke new forms

### ISSUE THREAD

**Issue by barneycarroll** [auth0/lock#151]
[As seen in this fiddle](http://jsfiddle.net/barney/pw226jao/) (go to the sign in page, go back to the home page, _then_ go back to the sign in page), once one of the Auth0Lock `show` methods has been used, you cannot `show` again for the same instance. This is because each Auth0Lock instance binds to a container on its first show, and will then [silently short-circuit the form display function if it already has a bound container](https://github.com/auth0/lock/blob/72057654d4f69c768d54ce2037fd58ebf79dbef3/index.js#L324).

Current workarounds:
* Create a new Auth0Lock instance every time you want to show a new form
* Manually delete the instance `$container` property
* Monkey-patch the `show` method to do the above for you

**Comment by barneycarroll** [comment]
This fixes it for me, but I can't vouch for whether the check served any purpose in the first place. This might break other functionality.

```javascript
void function alwaysShow(){
	var key    = 'show';
	var proto  = Auth0Lock.prototype;
	var config = proto[ key ];

	proto[ key ] = function removeContainerRef(){
		delete this.$container;

		return config.apply( this, [].slice.call( arguments ) );
	};
}();

**Comment by cristiandouce** [comment]
@barneycarroll yes you can. You just have to:
 
```javascript
lock.hide(function () {
  lock.show(options);
})
```

Which is much easier.

Or you could just create a new instance of the lock, no issues there.

**Comment by barneycarroll** [comment]
Aha! So correct usage is to explicitly invoke `hide` whenever I'm done with a form?

**Comment by cristiandouce** [comment]
This is the thing with lock. The idea for that `shortcircuit` is to avoid that you multiply call:

```javascript
lock.show({ container: "a", connections: ['database']})
lock.show({ container: "b", connections: ['facebook']})
lock.show({ container: "c", connections: ['twitter']})
lock.show({ container: "d", connections: ['linkedin']})
```

Because the options of instance are replaced with the ones from the latest invokation. This means that when you submit signin with database in your container `a` it won't recognize the database connections from the configuration.

So, if you want to have multiple locks in the page you can instantiate as many as you want.

If you want to work with a single instance what you pass away with a service, then yes... you need to hide it before showing. Which will dettach it from it's container and re-render again.

Or, whenever you get in the page, you can also create a new Lock intance with no problem, as long as you clean every reference to the latest lock.

```
(new Lock('cid', 'domain')).show(options);
```

**Comment by barneycarroll** [comment]
Thanks for the insight. The API makes more sense when you consider edge cases, and I appreciate it's kind of impossible to document these without overwhelming the user.

I've decided to take the approach of explicit hiding on form unload. Thanks again for the explanations.

I assume the reasoning for a hide callback is to cater for outgoing animations?

For posterity, here are two fixed forks of the original fiddle:
* [This one always calls `hide` before it calls `show`](http://jsfiddle.net/barney/m6tfvh3p/). It's probably best for uni-directional view frameworks where you want to avoid callbacks as far as possible.
* [This other one makes sure each initialised form container takes responsibility to hide the moment it's removed from the DOM](http://jsfiddle.net/barney/35zfg6uu/). Might be better for dynamic, multi-directional apps.

**Comment by cristiandouce** [comment]
Second one is much cleaner. Good examples both! :dancer: Thanks!
