### ISSUE TITLE
/user/ssodata throws 404 on new tenant

### ISSUE THREAD

**Issue by luisguerra** [auth0/lock#1525]
### Description

The use case I'm trying to acomplish is login with a user account in my tenant, logout and when re-enter the login the `Last time you logged in with` screen should be displayed

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [ ] Are you reporting this to the correct repository?
* [ ] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: 11.11.1
* Browser version: Chrome
* OS: Windows 10

### Reproduction

Go to [my login page](https://inmuebles.auth0.com/login?state=a9Sm_cORvkd2Nfs-_SvC1vzIKVmSPfTN&client=ZIt2_7alkaiuy-bifxBKrcPiy06IerwV&protocol=oauth2&response_type=token%20id_token&response_mode=fragment&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fcallback&scope=openid%20profile%20email&audience=https%3A%2F%2Finmuebles.auth0.com%2Fuserinfo&nonce=bm4jCCJ9HwrkFOMlJejIRXiLMynguxXB&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS44LjAifQ%3D%3D) open DevTools and see that the `/user/ssodata` endpoint is returnind 404 which holds the information about the last user entered

**Comment by luisrudge** [comment]
Thanks for bringing this up. This happens because new tenants have our new SSO flow, which doesn't even show the login page if doesn't need to. So we decided to remove the /ssodata endpoint for new tenants, since it's not needed anymore. The problem is that for unauthenticated users, lock will still call the /ssodata endpoint. We're working on a solution as we speak but, in the meantime, you can disable the `rememberLastLogin` so lock doesn't call /ssodata when it loads.
