### ISSUE TITLE
Add On Signup success event

### ISSUE THREAD

**Issue by Rockson** [auth0/lock#1534]
This is a feature request.
At the moment there is no way to run some code after signup succeded, it would be useful to add an event on signup success.
A use case could be to redirect the user to a page after signup (for example a page that informs the user that he will receive a confirmation email soon)

**Comment by luisrudge** [comment]
For your specific scenario, you could customize [this string](https://github.com/auth0/lock/blob/master/src/i18n/en.js#L52) and set [`loginAfterSignUp:true`](https://github.com/auth0/lock#database-options). This will show whatever message you want.

A 'signup success' event is a tricky feature to add because federated connections would never trigger this event, which might make it unreliable at best.
