### ISSUE TITLE
sso error message is not removed from forgot password page

### ISSUE THREAD

**Issue by luisrudge** [auth0/lock#1540]
### Description

Once an SSO email is introduced in the forgot password page, the error appears correctly. But when this email is edited and stops being an SSO, the button gets activated but the error message remains.

**Comment by amora-uz** [comment]
Hello, I've found another flow that reproduces the same error. Maybe the cause is exactly the same.
The steps to reproduce it are:
- Enter an email and a WRONG password.
- Click login button.
- Error message appears (wrong email/password combination).
- Change the email to an SSO one.
- "single sign on enabled" message appears but the previous error remains.

**Comment by luisrudge** [comment]
duplicated: https://github.com/auth0/lock/issues/1416
