### ISSUE TITLE
Fields and buttons order

### ISSUE THREAD

**Issue by mirkods** [auth0/lock#1545]
### Description
The default configuration shows social logins OR username/password fields, how can I have invert the order to have username/password fields OR social logins?

### Prerequisites

* [x ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x ] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [ x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x ] Are you reporting this to the correct repository?
* [ x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment
* Lock version: 11.11.0
* Browser version: All
* OS: Mac 

This is just an example:

<img width="252" alt="schermata 2018-11-09 alle 16 53 43" src="https://user-images.githubusercontent.com/2368194/48272922-0d7aed80-e440-11e8-9593-b347fcc37ae0.png">

**Comment by luisrudge** [comment]
There's no option to do that and it's not something we're considering.

**Comment by mario-moura-silva** [comment]
Hi @luisrudge,

Does it make sense to keep this feature off the backlog? The [Universal Login Experience] (https://auth0.com/blog/introducing-the-new-auth0-universal-login-experience) follows this suggestion.

It would be great for Lock.js to offer almost the same feature as Universal Login Experience. Otherwise, Lock.js will lose the benefits of continuing to use, and Universal Login Experience, on the other hand, does not offer the same ability to customize the login page as Lock.js.
