### ISSUE TITLE
ReferenceError: cb is not defined

### ISSUE THREAD

**Issue by KevinBusse** [auth0/lock#1700]
* Lock version: 11.17.0 (possibly since 10.0.0)

There is an undefined function `cb()` called.

Was introduced with: https://github.com/auth0/lock/commit/7ea5c2271a63f6b09b19443ceddb4a17bc48adbb#diff-d9c9f2bcdfe158127d37c0b3e33e8d0eR168

![image](https://user-images.githubusercontent.com/1112379/61444694-31d28680-a94c-11e9-924a-ad461b5ce82e.png)

**Comment by luisrudge** [comment]
@KevinBusse I'll start investigating this issue this week, but I need more info on how are you running this, how is your client set up etc. Your PR makes sense and I agree the current code has a bug, but this code lives in the repo since forever and we had no issues about this before, which makes me believe that this codepath doesn't get called that often. So, to better understand what's going on, can you create a simple repro that will 100% hit this? Thanks!

**Comment by KevinBusse** [comment]
The code path is dependent on the widget sliding in and the `height` != `orginalHeight`.

An interval will be started, and the callback will be stored. Usually the interval will be cleared when the desired height is reached. We cannot reproduce the issue 100%, but we assume that an inpatient developer (maybe some power users) that logs in during that resizing triggers the unmounting and since the intervall still exists the callback called but undefined.

**Comment by luisrudge** [comment]
I'll accept the PR because the current code is just wrong haha, there's no `cb` at that time, so the PR is correct and safe. But I couldn't reproduce this even when using chrome dev tools to reduce the animation speed to 10%. Pretty weird indeed! Maybe someone was automating the login? 🤔
