### ISSUE TITLE
Upgrade react to 16.x

### ISSUE THREAD

**Issue by petrogad** [auth0/lock#1722]
### Description

Please upgrade React in package.json to support version 16.x. Right now projects using 16.x that also use auth0's lock have two instances of react in their bundle to satisfy lock0's implementation.  

This is mentioned in #1564 #1067 however each of these issues have been closed.  Can we maintain an open issue until the resolution of react being upgraded to 16?

Thank you!

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

**Comment by luisrudge** [comment]
I understand your frustration, but we can't migrate to react 16 without releasing a new major version and, currently, there's no ETA for a new major version. There's more context here: https://github.com/auth0/lock/pull/1142#issue-146055423

In the meantime, you can use yarn resolutions to pin react@16 to your project. This will prevent two react copies from being bundled with your application. Here's an example: https://github.com/luisrudge/lock-react16/blob/master/package.json#L17-L19

We're leaving GH issues for actual bugs, that's why we're keeping issues like this one closed.

**Comment by stevehobbsdev** [comment]
👋🏻 We now have a v12 beta version that includes an upgrade to React 18 - please see [this issue](https://github.com/auth0/lock/issues/2224) and let us know what you think, or if you encounter any problems!
