### ISSUE TITLE
Strings have dots not standard

### ISSUE THREAD

**Issue by yvonleclerc** [auth0/lock#1741]
The use of period is overused in  https://github.com/auth0/lock/blob/master/src/i18n/en.js 

Here are recommendations more aligned with industry standard.

**Do not use periods:**

- at the end of a title or heading
- at the end of index entries
- after dates or signatures
- in abbreviations or contractions

See the Microsoft writer guide for conventions (https://docs.microsoft.com/en-us/style-guide/punctuation/periods) for error messages and other strings but in general, do not use end punctuation if the string is one sentence or a phrase. Note that this MS standard says no end punctuation if in the UI. If it is a block of text in the UI (where I hope we're headed for some audience and kinds of content/problem) still punctuate it like a block of text ...

**Comment by joshcanhelp** [comment]
@yvonleclerc - Appreciate the report here and the reference link as well. As much as we'd love to perfect these messages, it's a bigger job than just removing a few periods:

https://github.com/auth0/lock/tree/master/src/i18n

Since this is more of a style thing and such a large undertaking, I'm going to close it for now. I am, however, going to raise it as an improvement suggestion for all of our libraries.
