### ISSUE TITLE
Frequent session out in safari

### ISSUE THREAD

**Issue by gokulkraju1993** [auth0/lock#1752]
I am facing an issue in safari. in chrome and firefox its working fine.in safari frequent session out is occurring when we call function lock.checkSession for silent auth.

USING : Single page Application 
lock version : "11.18.0",
auth0.js varsion : "9.11.2",

#auth0 configurations used : 
        auth: {
            redirect: false,
            sso: true,
            redirectUrl: environment.auth0.callbackURL,
            responseType: 'token'      
        }
#log in auth0 : 
![Capture](https://user-images.githubusercontent.com/50861184/68917366-ee6c1580-078f-11ea-8af6-d2bd5fafbe94.JPG)

**Comment by stevehobbsdev** [comment]
You're most likely running into [Safari's ITP2 protection](https://www.impression.co.uk/blog/12082/safari-itp-2-0-what-is-it-and-are-you-ready-for-it/), which prevents transmission of what it deems to be third-party tracking cookies. Unfortunately the cookie that allows you to silently authenticate with Auth0 (and many other auth providers) gets caught up in this and simply doesn't work. You will run into the same issue with the Brave browser, for example, which all of its sheilds up.

Please have a read of [this Auth0/ITP2 doc](https://auth0.com/docs/api-auth/token-renewal-in-safari) for more information. The article mentions that you can get around this with Auth0 by using [Custom Domains](https://auth0.com/docs/custom-domains), but please bear in mind this is a **paid feature**.

Otherwise, you're in the unfortuate position where you might be stuck. However, we are well aware of the issue and working to resolve it.
