### ISSUE TITLE
Checbox validation

### ISSUE THREAD

**Issue by carlosMedrano27** [auth0/lock#1813]
Using checkbox as a custom signup field is not triggering the validator for the checkbox to be checked

**Comment by stevehobbsdev** [comment]
Hi @carlosMedrano27 , can you share your configuration for the custom checkbox?

**Comment by stevehobbsdev** [comment]
Closing this for now as unreproducable without configuration info.

@carlosMedrano27, if this is still an issue, please raise a new issue and complete the GitHub template as provided, with as much information as possible. Include version numbers, and an example of your current configuration so that we may help you.
