### ISSUE TITLE
"Something went wrong." error with Auth0 lock version v11.25

### ISSUE THREAD

**Issue by peteschmitz** [auth0/lock#1930]
### Describe the problem

> Our login page became non-functional today, with an ambiguous error.

![image](https://user-images.githubusercontent.com/3190970/94869498-4b99a580-03fa-11eb-9d48-0819dde5f19d.png)

### What was the expected behavior?

> For our login page to remain functional, as it had been yesterday.

### Reproduction

1. Create a "Custom Login" page in Auth0, using the standard HTML
2. Use an older version of lock (we were on https://cdn.auth0.com/js/lock/11.25/lock.min.js)
3. Encounter the above message when attempting to access the login.

### Environment

- Lock version 11.25
- Custom Login (which we _have_ modified ourselves)

----

I have no doubt that it's our fault for either implementing an unintended configuration on our custom login page or we naively referenced a deprecated version (and ignored messages to properly update). However:

- Simply referencing v11.27 resolved the error.
- We haven't made changes within the last 48 hours to our custom login page (that I'm aware of). Is there additional information from the auth0/lock side that can assist our investigation?
- If we were referencing a version which is now obsolete, how can we stay on-top of these breaking version dependencies/changes in the future?

**Comment by saltukalakus** [comment]
@peteschmitz this issue was related to [this incident](http://status.auth0.com/incidents/28lwp6hyxbwq?u=6hrnyjc79phk). 

It affected customers who didn't configure custom domains properly. Though the issue was resolved with a change on our end, you may want to update your application configuration if it isn't conformant to the following links. 

* For universal login with Lock you may find it [here.](https://auth0.com/docs/custom-domains/configure-features-to-use-custom-domains#universal-login)
* For embedded login with Lock you may find it [here.](https://auth0.com/docs/custom-domains/configure-features-to-use-custom-domains#embedded-lock)

**Comment by saltukalakus** [comment]
@peteschmitz actually it should be related to [this](http://status.auth0.com/incidents/d84prf8wf2bg) . These two incidents were connected but they are both resolved. Sorry for the inconvenience.

**Comment by saltukalakus** [comment]
As a side note, you may find [Auth0 status](https://twitter.com/auth0status) on twitter useful.

**Comment by peteschmitz** [comment]
@saltukalakus Thank you for the info - we had checked the status page when we first encountered the issue (~18:55 UTC), so we missed the above incident posting.

We'll definitely look into better monitoring/subscription on our end.

Best,
Pete
