### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'descriptor.get') in Safari

### ISSUE THREAD

**Issue by mivanyna** [auth0/lock#1965]
### What was the expected behavior?

Login modal should be shown

### Reproduction

First error 403 received:
![image](https://user-images.githubusercontent.com/10868397/107758372-72180780-6d2f-11eb-99d2-c5f3e0a4bfbf.png)
![image](https://user-images.githubusercontent.com/10868397/107758340-67f60900-6d2f-11eb-91a7-a66d8c7824ae.png)
And some local variables:
![image](https://user-images.githubusercontent.com/10868397/107758407-80662380-6d2f-11eb-8f5a-adbb13a370fb.png)

- Step 1. Open https://console.magine.com/ in safari and press login
- Step 2. Nothing happens - error is logged in browser's console
- 

### Environment

- **Version of this library used:**
-  "auth0-js": "9.14.0",
    "auth0-lock": "11.27.1",
- **Which framework are you using, if applicable:**
- Angular 11
- **Other modules/plugins/libraries that might be involved:**
- no idea
- **Any other relevant information you think would be useful:**
- with the latest version issue still exists:
- "auth0-js": "9.14.3",
  "auth0-lock": "11.28.0",
- Have noticed that this issue appears in case if **there is no auth0 cookies**. Once you have logged in - issue doesn't appear.

**Comment by adamjmcgrath** [comment]
Hi @mivanyna - this looks like it might have been fixed by https://github.com/facebook/react/pull/12875#discussion_r189641059 which made it into react-dom `15.7.0` 4 months ago

You're currently on `15.6.2`, but you should be able to pick up `15.7.0` with lock if you run `npm update react react-dom`

You can check which version of react lock is using with `npm ls react-dom`

**Comment by mivanyna** [comment]
Thank you!
