### ISSUE TITLE
Failed Silent Auth in Chrome & Safari, not Firefox

### ISSUE THREAD

**Issue by chmac** [auth0/lock#2017]
### Describe the problem

Users can login via Firefox and Chrome **but not Safari or Chrome in Incognito**

An attempt to login in Chrome produces the error `WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.` Our tenant logs show 2 errors in sequence `Failed Silent Auth` then `Failed Cross Origin Authentication`.

But if we login via Firefox, then we see 2 times `Success Cross Origin Authentication` in our tenant logs

### What was the expected behavior?

We would expect to see successful login across browsers.

### Reproduction

This issue is reproducible in production only, but not in our development setup.

The app is running in production here (please post an issue if you create a test user so we can clean it up): https://expenses.kiezburn.org/

You can see the code that instantiates the lock here:

https://github.com/GenerousLabs/community-expenses-submission/blob/2b41b054dd5f2734565f68249e9a9219b4a6b996/frontend/src/services/auth/auth.service.ts#L44-L53

Neither the `authorization_error` nor `unrecoverable_error` events will fire in Safari (nor in Chrome Incognito).

### Environment

- "auth0-lock": "^11.30.4",
- "react": "^16.12.0",

I suppose this is related to some browsers blocking cross origin cookies. I'm not sure what the issue is specifically, but my assumption (perhaps naively) would be that the Auth0 lock would handle this, and somehow send users into a sensible fallback flow or something.

**Comment by stevehobbsdev** [comment]
@chmac Thanks for reporting this. Cross-origin login requires the use of third-party cookies, which are unfortunately blocked in all the non-working browsers that you mention. This is an issue that's a but out of our control, and you're absolutely correct that it's related to browsers blocking those cookies.

We don't have a fallback for embedded Lock other than using a [custom domain](https://auth0.com/docs/custom-domains), which is unfortunately a paid feature. This would mean that the cookies exist on the same origin and you won't run into this cookie blocking issue.

We're not able to solve this problem within this particular SDK as we're unable to take advantage of [rotating refresh tokens](https://auth0.com/docs/tokens/refresh-tokens/refresh-token-rotation) here.

Your other option beyond custom domains is to migrate to using the Universal Login Page instead of embedding Lock intor your app. As you're using React, we publish [Auth0 React](https://github.com/auth0/auth0-react), which is a package for React that works with the ULP. This SDK is also able to take advantage of refresh tokens and somewhat mitigate the effects of third-party cookie blocking.

Hope that helps somewhat although I appreciate it doesn't immediately solve your issue. Closing for now but happy to continue the conversation.
