### ISSUE TITLE
Authenticated event is not thrown on /users page. Only works on / route.

### ISSUE THREAD

**Issue by Abdulla1995** [auth0/lock#2066]
### Describe the problem

When I login on` "/"`  URL authenticated event has been thrown . But when I go to `"/users"` and try to login by auth0, the `authenticated `event is not thrown. I use `lock.show()` method to show the login popup.

### What was the expected behavior?
Expected `authenticated `event to be thrown nevertheless the login page `URL`.

### Reproduction

- In the lock options object I have set `state `to current login pathname. I want to use it after redirect back to the application but `authenticated` event is not thrown if the current path equal to "/users"
 ```
auth: {
    responseType: 'token',
    params: {
      state: window.location.pathname,
    }
  },
```
- If I delete state property it works as expected and event authenticated is thrown. If I use string as "/users" in the `state ` it also works. Only `window.location.pathname` version is breaks authenticated event on other urls but not on `"/" `home url.
### Environment

- **Version of this library used: "auth0-lock": "^11.31.1",**
- **Which framework are you using, if applicable: "vue": "2.6.14",**

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @Abdulla1995. Can you tell me about the intended use case here? Are you trying to store a path to redirect your users to after login?

If so, the recommended way to do this is to store that value in some kind of transaction cookie or local/session storage for retrieval in the `authenticated` event, rather than pass it to the authentication server via the `state` param. 

The `state` param as specified in your example refers to the OAuth 2.0 state param and is there to prevent XSRF attacks, and should be a random unguessable value (see [Cross-Site Request Forgery in RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12)). If you remove the `state` parameter from your configuration, this value will be generated for you.

Hope this helps.
