### ISSUE TITLE
`flashMessage` not shown if provided in `Auth0Lock` constructor options

### ISSUE THREAD

**Issue by dpraul** [auth0/lock#2336]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/lock#readme) and [Examples](https://github.com/auth0/lock/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/lock/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If an `Auth0Lock` instance is created with a `flashMessage` parameter in the options, it will be ignored. The `flashMessage` parameter can only be provided during `lock.show()`

### Reproduction

1. Initialize lock with a message: `new Auth0Lock(CLIENT_ID, DOMAIN, { flashMessage: { type: 'error', text: 'Error!' } })`
2. Call `lock.show()` without a message.
3. Observe no message shown :(

### Lock version

12.0.2

### Which browsers have you tested in?

Chrome

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @dpraul, according to the API we should be accepting that at constructor time, I will look into it.

In the meantime, can you elaborate on the use case so I understand your scenario better?

**Comment by dpraul** [comment]
In our logic for building the `Auth0Lock`, we have some particular environments where we want to always show a message in the popup. Right now I have a workaround to pull the `flashMessage` field from the configuration object and reuse it in the call to `lock.show` until this is fixed.

**Comment by stevehobbsdev** [comment]
I've been looking at this problem this week, thanks again for your patience. By the looks of it, this is actually not supported by the library today (it's not a bug as such, it was never actually implemented to work this way, and `flashMessage` can only be specified in a call to `show()`). The bug here is that the readme is incorrect, I'm about to raise a PR to sort that out.

We don't have plans to implement this today unfortunately. Please continue to use the method you have used so far to specify the value for `flashMessage`.
