### ISSUE TITLE
Bug: Form doesn't reset to login after failed autoLogin after signup

### ISSUE THREAD

**Issue by baer** [auth0/lock#257]
If `loginAfterSignup` is `true` (the default behavior) and a user's login fails after signup the form values don't reset and the form stays in "signup" mode. In order to clear it you have to click the "cancel" button.

**Comment by gnandretta** [comment]
I can confirm this is happening.

After a successful signup, [Auth0Lock._signinWithAuth0](https://github.com/auth0/lock/blob/d7dbd1d1738dd1f5ffa8ff18476fe445ba4fd767/lib/mode-signup/index.js#L308) is called with an instance of `SignupPanel` from which it queries the user name and password to log the user in. That same instance is also rendered when the login fails.

We'll need to schedule some time to tackle this because I couldn't find a quick solution.

**Comment by baer** [comment]
Thanks for the quick response! I'm looking forward to having a working Auth0 pipeline in my app.

**Comment by baer** [comment]
@gnandretta - Any updates on this? I can't roll out Auth0 until this is fixed :/

Workarounds:
* I could turn off autoLogin but your dashboard doesn't index users until they have attempted to sign in so this will result in our admin trying to manage a bunch of users that appear to not exist.
* I could show and hide Lock to reset it but then I lose all of the nice validation messages you provide which would be pretty confusing to a user.

Any ideas?

**Comment by gnandretta** [comment]
@baer when do you plan to launch? I'll fix it tomorrow

**Comment by baer** [comment]
I will launch when I get all of my auth stuff straightened out and it is now looking like I have a bit of backend work to do in order to expire a token. Whenever you get to it would be great but I won't launch until late this week or early next week it looks like.

**Comment by gnandretta** [comment]
@baer should be fixed in _7.12.2_.
