### ISSUE TITLE
Callback function is run immediately in v10

### ISSUE THREAD

**Issue by dharness** [auth0/lock#343]
Using the new configuration method, placing the callback in the constructor:

    var lock = new Auth0Lock(clientId, domain, {}, function(err, result){
        alert('breakast is important')
    });

runs right away. Is this the desired behaviour? Why does this happen? How can I prevent it?
http://puu.sh/o1et5/9004584b7c.png

The function does not appear to run on login either. Is there something I am missing?

**Comment by gnandretta** [comment]
Hi @dharness, Lock now works on redirect mode by default and the callback is run every time you instantiate the widget so you don't have to worry anymore about stuff like parsing the hash and getting the user profile.

I've updated the [docs](https://auth0.com/docs/libraries/lock/v10) with more details about the changes. Hope that helps.

**Comment by Brightergy-BrishaPote** [comment]
@gnandretta we're facing the similar issue here.

Below is our code:
```
import React from 'react';

export var Login = React.createClass({
  componentWillMount: function() {
      var initializationOptions = {
        auth: {
          params: {scope: 'openid email name user_metadata app_metadata'},
          redirect: true,
          redirectUrl: this.props.auth0_callback,
          responseType: 'token',
        }
      }

      this.lock = new Auth0Lock(
        this.props.auth0_client_id,
        'ourapp.auth0.com',
        initializationOptions,
        function(err, result) {
          console.log('Called!!!')
          if (err) {
            console.log('Error with auth0');
          }
          if (result) {
            console.log('Successfully logged in!!!');
            localStorage.setItem('userToken', result.idToken);
            this.lock.getProfile(result.idToken, function(error, profile) {
              if (error) {
                console.log('Error retreiving user profile');
              }
              if (profile) {
                localStorage.setItem('userProfile', JSON.stringify(profile));
              }
            });
          }
        }
      );
  },

  render: function() {
    this.lock.show();
    return null;
  }
});
```

The `console.log('Called!!!'` executes immediately when the login page is loaded (which is as per your description above(`the callback is run every time you instantiate the widget`). However, when the user is successfully logged in or an error occurred, the callback is not called and we can't get information stored in localStorage.

**Comment by colllin** [comment]
For others who find this, it seems this is how we're meant to use v10:

    displayAuthZeroLock: () => {
        if (this.state.lock) return;

        const lock = new Auth0Lock(this.props.env.AUTH0_CLIENT_ID, this.props.env.AUTH0_DOMAIN, {}, (error, result) => {
            console.log(error, result);

            if (result) {
                // Handle logged-in user
                return;
            }

            lock.show();
        });

        this.setState({lock: lock});
    }

The callback passed to `new Auth0Lock(...)` is always executed immediately.  If the URL contains a token (as it does after being redirected back from Auth0), the callback receives a `result` and should handle the incoming id_token.  If it doesn't contain a result, then you should show the Lock.  I track the lock in `this.state.lock` to avoid showing multiple dialogs.  You might not need to do that if you only call this function once, but I need to call it on every change to props since the clientID and domain come in through props.

**Comment by gnandretta** [comment]
@Brightergy-BrishaPote We have changed the API in the latest release.You now have to listen for an authenticated event instead of providing the callback. For more information see https://auth0.com/docs/libraries/lock/v10/installation.

The issue might be related with the redirect url or, if you are building a SPA, with the routing of your application. But from the information I have, I can't tell for sure.

If you still experience the same problem after upgrading, please open a new issue and provide a minimal sample project so we can take a look at it. Thank you.

**Comment by Brightergy-BrishaPote** [comment]
Thanks for the response @colllin  @gnandretta . We were able to figure out the issue. It was related with how the lock was being initialized and how we were grabbing token once logged in.
