### ISSUE TITLE
[Version 10] Invariant Violation with React and Webpack

### ISSUE THREAD

**Issue by bbar** [auth0/lock#353]
My application is targeting react v15.0.1 and auth0-lock v10. Everything's being bundled together by Webpack.

```
import Auth0Lock from 'auth0-lock/lib/classic';
let lock = new Auth0Lock('id', 'domain');
```

`lock.show()` throws the following:

Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

I haven't dug too far into this, but it seems that the version of react auth0-lock is targeting (0.14.5) is conflicting with the version my application is targeting (15.0.1). I've worked around this by adding the follwoing to my webpack.config.js file:

```
resolve: {
  alias: {
    "react": __dirname + '/node_modules/react',
  }
}
```

So now, instead of Webpack bundling 2 versions of React (the version auth0-lock is targeting and the version my application is targeting), it's only bundling the version my app is targeting, and it tells anything else that requires React to look no further than that version.

Although things are working fine right now, I can see problems creeping up in the future. Is anyone aware of a better way to do this using Webpack?

**Comment by gnandretta** [comment]
We have updated the React dependency and we are less strict about its version. Thanks.

**Comment by gilesbutler** [comment]
I still get this error on ```10.3.0``` - the only way to fix it was using @bbar's solution above

**Comment by thedaniel** [comment]
I still get this error on `10.7.3`.

**Comment by RafaelCosman** [comment]
Still getting this on `10.14.0`.

**Comment by luisrudge** [comment]
how are you importing lock?

**Comment by RafaelCosman** [comment]
`import Auth0Lock from 'auth0-lock'`

I'm using TypeScript with `ts-loader`.

**Comment by luisrudge** [comment]
Can you provide a sample project?

**Comment by samcorcos** [comment]
@luisrudge I ran into the same issue. Here's a sample project using an ejected version of `create-react-app`:

https://github.com/samcorcos/auth0-invariant-violation

The only thing I changed was the place that React and ReactDOM are recognized. I'm no longer using the `react` package, but the CDN [here](https://github.com/samcorcos/auth0-invariant-violation/blob/master/public/index.html#L19-L22) and the webpack config [here](https://github.com/samcorcos/auth0-invariant-violation/blob/master/config/webpack.config.dev.js#L211-L214)

## Instructions

Add valid public keys [here](https://github.com/samcorcos/auth0-invariant-violation/blob/master/src/auth.js#L3-L4)

```
$ yarn
$ npm start
```

Click on the button in the top right to log in. 

The page won't responsively update on successful login (because I'm lazy), but you will see the error logged to the console and the login will fail.

Let me know if you need any more information

**Comment by luisrudge** [comment]
@samcorcos it's because of the `react-addons-css-transition-group` package. It imports `react/lib/ReactCSSTransitionGroup`, so you have to alias that as well.
![image](https://cloud.githubusercontent.com/assets/941075/25684620/cbb272ae-3038-11e7-9834-4e99e12a9450.png)


This might get fixed once we fix https://github.com/auth0/lock/issues/994
