### ISSUE TITLE
Spaces not allowed in Username and error message missing

### ISSUE THREAD

**Issue by dleeward** [auth0/lock#375]
When a user enters a username containing a space, Lock highlights the field but does not give an error message indicating that you cannot use a space. But WordPress allows spaces in usernames, so the widget should have some options in setup to specify what types of characters are allowed. This is a blocker for us implementing Auth0 in production. #374 discusses the error message being missing, but a space is not necessarily illegal but actually desirable for some sites.

**Comment by hzalaz** [comment]
@dleeward we are going to fix the missing message error soon (https://github.com/auth0/lock/issues/374). 
About allowing spaces in usernames, currently the Auth0 API has the following restrictions regarding usernames:

* Username can only contain alphanumeric characters and '_'. 
* Username cannot have more than 15 characters.

So even if we allow spaces the server, the request to signup will fail because of this.

**Comment by dleeward** [comment]
I assume you will put that in the error message.

**Comment by hzalaz** [comment]
Yes

**Comment by hzalaz** [comment]
@dleeward will be closing this one in favor of #374. If you want please submit a feature request [here](http://feedback.auth0.com) so we allow this in the Auth API. We are enforcing this since this can be used to authenticate instead of the email with the API. 
If you need something like a display name, you can store it inside `user_metadata` object and then use it in your site.
Currently Lock 9 doesn't have this feature but [Lock 10 beta](https://auth0.com/docs/libraries/lock/v10/new-features#custom-sign-up-fields) has it. (not sure if wordpress can use Lock 10)

**Comment by dleeward** [comment]
That wold be helpful for new users if it can be integrated into WP-Auth0 but won't help with migrating current users.
