### ISSUE TITLE
[v10] Callback not called after successful login 

### ISSUE THREAD

**Issue by kadikraman** [auth0/lock#445]
When migrating from v9 to v10, callbacks for successful login stopped working. This is our code:

```js
const lock = new Auth0Lock(
      Auth0Variables.AUTH0_CLIENT_ID,
      Auth0Variables.AUTH0_DOMAIN,
      { auth: { redirect: false } },
      (error, result) => console.log(error, result)
);
lock.show();
```

Although the lock shows up, we log in successfully and see a "Thank you" message, we never receive any log.

**Comment by gnandretta** [comment]
We have changed the API in the latest release.You now have to listen for an `authenticated` event instead of providing the callback. For more information see https://auth0.com/docs/libraries/lock/v10/installation.

I have tried your sample with v10.0.0-beta.4 and the callback is executed. If you still experience the same problem after upgrading, please provide a minimal sample project so we can take a look at it. Thank you.

**Comment by kadikraman** [comment]
Ah, that worked, thank you. I was still referring to the old documentation.

**Comment by stanislasdrg** [comment]
I will add this as a comment for future reference here, as it took me some time to narrow down the issue with Lock v11.
The callback not called error could also be caused by Lock blocking requests if third party cookies are not allowed in the browser. The default with Safari & Brave now.
The bad news is that you now have to pay for auth0 Lock(v11) embedded to work with third party cookies. The solution is to use the hosted version of Lock, using the `authorize` method instead of `show()`.

The reason is that cross-origin authentication requires cross-domain cookies to establish an SSO session in the authorization server.

The documentation is very misleading regarding this.

Some more info on [this thread](https://community.auth0.com/t/unable-to-configure-verification-page-error-on-hosted-login/9214/29)
