### ISSUE TITLE
[V10@10.0.0-rc.2] Setting explicit redirect URL prevents authentication because hash values aren't appended to URL

### ISSUE THREAD

**Issue by wallslide** [auth0/lock#479]
Setup: 

1. Create a `new Auth0Lock` with the `redirectUrl` option set.
2. Sign-in with Twitter
3. User is redirected back to desired redirectUrl, but no authentication occurs because the necessary information appended to the URL was missing.

When the browser returns from the auth0 login, the only thing that is appended to the URL is a query parameter called `code` that looks like this `7dXrNhxFrfjPa8oX`.

If I don't set the redirectUrl, then the user is eventually authenticated just fine.

**Comment by wallslide** [comment]
Okay, solved my own problem:

As per the documentation [here](https://auth0.com/docs/libraries/lock/customization#responsetype-string-), if a callbackUrl (now called `redirectUrl` in v10) is set, the response type is changed from `token` to `code`. My suggestion is that now that the redirect method is default, the response type shouldn't change to `code` when setting an explicit `redirectUrl`

**Comment by gnandretta** [comment]
Hi! The `code` response type is used for server flows, while the `token` response type is used for client flows. We default to a code response type when you provide a redirect url because it is most likely that you'll be using a server flow. We will review the docs and keep an eye on this. Thanks for your feedback.
