### ISSUE TITLE
show event triggered before showing the widget

### ISSUE THREAD

**Issue by rafalwrzeszcz** [auth0/lock#510]
`show` widget should be fired when the widget is already displayed (or a new event should be introduced for that). It's impossible to handle the UI in a predictible way (`setTimeout()` hacks from your test suite? really?).

**Comment by gnandretta** [comment]
Hi, the `show` event was included to support scenarios where you only need to know that the lock `show` method was called. For example, to keep metrics about logins.

Tests use `setTimeout` because I try to add events only when I know it would have a real use case from Lock users. Can you explain what is your use case? What do you mean by "the widget is already displayed"? is that the opening animation is done? or do you need to know that a given screen is ready to use? How does your UI need to be handled?

Thanks

**Comment by jennifer-mann** [comment]
I also would like to have an event available to listen to that triggers after the opening animation is done and the widget's UI is inserted into the DOM. 

My use case - only show email/pw fields on click of element in Lock UI: 
- I want to add an event listener that listens for clicks to a DOM element within the lock UI.
- On click of this DOM element, I would then display some other elements in the lock UI that I initially hid in CSS.

The `show` event currently triggers when the `show` method is called and before these elements are available in the DOM, so they're inaccessible.

**Comment by jennifer-mann** [comment]
I ended up setting up a mutation observer to listen for additions or removals from the childlist of this element: `div.auth0-lock-cred-pane.auth0-lock-quiet`. This triggers once where you can then add the code you want. I'm using `auth0-lock 10.0.0`.

My workaround code:

```javascript
lock.on('show', function () {
  const lock = document.querySelector('div.auth0-lock-cred-pane.auth0-lock-quiet')

  const observer = new MutationObserver(function (mutations) {
    // set event listeners or manipulate DOM elements here
  })

  observer.observe(lock, { childList: true })
})
```

**Comment by jeacott1** [comment]
+1 for a real ondomready/shown event
