### ISSUE TITLE
SPA problem #3

### ISSUE THREAD

**Issue by vladimirsakic** [auth0/lock#666]
I pass current state as params.state when login.
But can you tell me how to go to same state once login is done.
If I do something like:
lock.on('authenticated', function (authResult) {
    $state.go(authResult.state);
});
It’s not working.

I managed to have it work with:
lock.on('authenticated', function (authResult) {
    $timeout(function () {
        $state.go(authResult.state);
    }, 1);
});
But then it goes to home page and then to page in authResult.state and it’s not looking nice

**Comment by chenkie** [comment]
Aside from using `state` with Lock, the other option is to store the user's current location in local storage. When they click the login button, store the route they are currently on, and then use that to navigate on successful authentication.

It sounds like you're setting `$urlRouterProvider.otherwise('/home')` which will force the user to the home state after authentication. The reason they are forced there is that the route they arrive at after authentication isn't recognized. What you can do is specify a single location for the user to arrive at after authentication is complete in `auth.params.callbackURL`. Then you can define a route for this on your `$stateProvider` so that the user isn't forced to the home state due to an unrecognized route.

Here's a full sample that demonstrates this: https://github.com/auth0-samples/auth0-angularjs-sample/tree/ui-router-html5/08-Calling-Api

Have a read through the readme for more info.

**Comment by vladimirsakic** [comment]
if I try with setting callbackURL its not working, if I set it to http://localhost:1186/#/faq it still goes to http://localhost:1186/#/home, like it's not passing fragment.
And regarding first solution (passing state), if I understood right, using timeout is only option?
Thanks

**Comment by chenkie** [comment]
The above mentioned way of doing it works best if you're using `html5Mode(true)`. Since you're not, another approach you can take is to set your `callbackURL` to be the main route (`http://localhost:3000/`) and then create a rule for `$urlRouterProvider` which tells it where to take the user once an `access_token` is encountered in the URL bar (which happens on login).

```js
$urlRouterProvider.rule(function($injector, $location) {
  if (/access_token/.test($location.path())) {
    $location.path(localStorage.getItem('returnTo'));
  }
});
```

**Comment by vladimirsakic** [comment]
Thanks for new solution, looks like it should work. But I'm curious, first approach looks like cleanest one, only problem is that if you set state in lock 'authenticated' event it won't work. I don't understand why

**Comment by chenkie** [comment]
My guess is that it's a digest cycle issue, which is what wrapping it in a `$timeout` helps to avoid. This is a common issue with `$state.go` and isn't related to the `authenticated` event directly.
