### ISSUE TITLE
Ability to Override the Signup Endpoint

### ISSUE THREAD

**Issue by cancan101** [auth0/lock#701]
I am currently using the lock for logging in, etc and would like to use the sign up functionality in the lock. I would like the to use a custom endpoint on my site to process the signup, however (for validation, etc). It would be great if there were some way to override the endpoint used when signing up.

See also: https://auth0.com/forum/t/signup-in-lock-with-custom-endpoint/4123 

Perhaps as an additional param to: https://github.com/auth0/lock/blob/0149fe9dd741a29e36f1191efed6fe4ebf8ca581/src/engine/classic/sign_up_screen.jsx

**Comment by hzalaz** [comment]
Not sure we want to allow that kind of customization in Lock since it will expose way too many implementation details, ideally any extra validation should be handled by Rules so probably it's better to ask for Rules to be run on signup (although now it can be done checking the login count when the rule runs on Auth).

We are considering a way to provide a custom Lock engine (like classic or passwordless) but we haven't decided on the API the Engine needs to implement so we can document it.

The options available now are to implement a different sign up page and use `signUpLink` option to redirect to it or try using with the Rule if possible.

**Comment by cancan101** [comment]
> use signUpLink option 

We were trying to leverage as much of the UI already in the lock so as to avoid having to make out own elements.

> try using with the Rule

In some cases we are creating a new connection as part of the sign up process so I think this prevents us from going this route.

**Comment by hzalaz** [comment]
Closing this one. We don't have plans to allowing to change the signup endpoint url
