### ISSUE TITLE
SPA implementation

### ISSUE THREAD

**Issue by dpdragnev** [auth0/lock#703]
Hello,

I wanted to start by saying that I love the whole framework.  You have done a fantastic job with it and I can't wait to start using it in all my projects.

I am new to Auth0, so pardon the newbie question.  I have been digging through the documentation, but for the life of me I cannot make this work.

What I am trying to achieve is to use the Lock but without making a full postback and reload of the page.  I would like to be able to bring the Lock as a popup, authenticate the user, and receive the credentials without refreshing the page.  I followed the Angular example, but I am still getting a postback and a page refresh.  Also, the "authenticated" event never fires.  I am pretty sure that I am missing something in my setup, but I can't seem to find what.

Any help is greatly appreciated..

Thank you.

**Comment by chenkie** [comment]
The default mode for Lock is redirect, but you can choose popup mode by setting `auth.redirect = false` in your options object. Have a look here for more: https://auth0.com/docs/libraries/lock/v10/customization#redirect-boolean-

:)

**Comment by chenkie** [comment]
That being said, we don't recommend that you use popup mode, which is why redirect mode is the default. While it's easier to preserve app state using popup mode, there are caveats. For example, popup mode doesn't work in certain browser versions.

Depending on your needs, it might be better to preserve your app's state on login in something like local storage. You can then read these state details back after authentication is complete.

**Comment by dpdragnev** [comment]
Thank you Ryan for the quick response.  

I see your point.  Saving the state of the app and then reloading it after the redirect could be a good solution.

Best Regards,
