### ISSUE TITLE
Expose showLoginActivity function

### ISSUE THREAD

**Issue by elger** [auth0/lock#758]
We integrated Lock in our component but we want to be able to provide an individual back-to-login link in our outer component, if _forgotPassword_ screen is active. To be able to do this I thought of exposing the showLoginActivity function with something like the following:

```
diff --git a/src/core.js b/src/core.js
index 1830668..f73f63e 100644
--- a/src/core.js
+++ b/src/core.js
@@ -11,6 +11,7 @@ import {
   updateLock
 } from './core/actions';
 import { termsAccepted } from './connection/database/index';
+import { showLoginActivity } from './connection/database/actions';
 import * as l from './core/index';
 import * as c from './field/index';
 import * as idu from './utils/id_utils';
@@ -35,6 +36,7 @@ export default class Base extends EventEmitter {
 
     this.id = idu.incremental();
     this.engine = engine;
+    this.showLogin = showLoginActivity;
     const hookRunner = ::this.runHook;
     const emitEventFn = this.emit.bind(this);
```

Is that something that would be integrated by PR or do we have to rethink, because it is not compliant to Lock.

**Comment by hzalaz** [comment]
This would be something that will expose a bit of the internals of lock which is something we try to avoid @elger.

**Comment by elger** [comment]
Hmm, ok. So do you see another possibility to expose back-to-login function, maybe by an event that is emitted?

**Comment by hzalaz** [comment]
@elger sorry for the delay, we have not immediate plans to add to Lock a way to change the screens externally. The only workaround I can think of right now is trying to call `show` again with a different initial screen (hiding and showing will not work since you will see the swap animation).

If this work for you it's ok to fork it, that's why is OSS 😄 , but I wouldn't add this to master. Will add an item in our backlog to discuss it for the future (it's not a feature we are asked a lot tbh).

**Comment by elger** [comment]
No problem, meanwhile we implemented a solution aside of Lock because additionally, we had to resolve internal dependencies.
