### ISSUE TITLE
authorization_error not triggered

### ISSUE THREAD

**Issue by giulianf** [auth0/lock#778]
Hi,

The event "authorization_error" is never triggered because of process.nextTick function within action.js (L 256). 
I am using React app with Lock 10.x
Error message:
TypeError: (intermediate value).nextTick is not a function

Is it a known issue? 

BR,

**Comment by glena** [comment]
hi @giulianf in despite of it should not use `process.nextTick` and we are removing this, can you provide more info since I am not able to reproduce it (there is a shim for it)?

- [ ] Code snippet or sample project that reproduces the bug
- [ ] Lock version
- [ ] Browser & OS
- [ ] How are you bundling it

**Comment by giulianf** [comment]
Hi @glena 
I changed the process.nextTick to have setTimeout( f, 0) (the performance is not too much impacted).

I am using auth-lock.js v 10.8.1
Chrome in Mac os

I have a REACT client UI and I am using React-router.
To be logged, the user is redirected to Login page and the popup is displayed.
To fire the event "authorized_error" I fill in a non existing account.
After call "change password" API, process.nextTick failed.

I don't have a piece of code in order to reproduce it.
But with setTimeout it's working like a charm!

**Comment by glena** [comment]
Cool, we tackled this on #778. Anyway, there should be something related to your bundling since it worked fine with hours (there was a shim for it).
