### ISSUE TITLE
Auth0 rules do not propagate to lock UI if SSO = true

### ISSUE THREAD

**Issue by dshorowitz** [auth0/lock#804]
With lock v10 and SSO=true, errors thrown in auth0 rules are not caught before the user's browser is forwarded to the callback URL.

This makes it impossible to update the lock UI with the error messages from the rules, without a page refresh first.

See https://auth0.com/forum/t/auth0-rule-errors-in-lock-ui/4835/9 for a discussion on this topic.

Since you can catch rule errors in the lock UI if SSO=false, this seems inconsistent.

**Comment by hzalaz** [comment]
@dshorowitz let me see if I got this right, you need Lock to catch (and show) the error the rule raises after lock redirects to Auth0 to perform auth?

**Comment by dshorowitz** [comment]
Yeah so here's what I'm looking for.

1. User hits "log in" on our homepage
2. We call `lock.show()` to make the lock visible
3. User enters email + pass and hits "log in"
4. Login sent to auth0
5. Auth0 rules execute and an error is thrown (for whatever reason)
6. The error text is sent back to the lock
7. Lock widget is updated with the error text from the rule and the login is stopped.

The UI would look the same as the "Invalid username/password" error or the "User blocked" error.

The most important thing is that the user's browser doesn't redirect to a new page before the error message is shown. Instead, the error message should show up in the lock itself without a page refresh.

Does that make sense?

**Comment by glena** [comment]
@dshorowitz that is not posible.

The way auth0 works in that flow is that the rules run AFTER the user is redirected. This happen to make posible several different features like redirect rules and mfa. Because of that, it is not posible for lock to get the rule errors BEFORE the redirect.

Other flows like the one when SSO is disabled allows that BUT those features are not available or has restrictions.

The way to workaround this issue is to wait until the user is redirected back and on the `authenticated` event you will receieve the error. Since customers handles this errors in different ways lock will not show it automatically (we are discussing internally different ways to change this behaviour but we don't have a solutions in the short term) but you can use the `flashMessage` attribute to show them when you show lock like this:

```js
lock.on("authorization_error", function(error) {
    lock.show({
        flashMessage:{
            type: 'error',
            text: error.error_description
        }
    });
});
```

**Comment by luisrudge** [comment]
@jonathanappel you have to show the message in your app using whatever notification mechanism you already have
