### ISSUE TITLE
Cannot log in when {useHash: true} is used in RouterModule.forRoot() with Angular 2

### ISSUE THREAD

**Issue by stefanruijsenaars** [auth0/lock#806]
This is likely a JWT issue, but crossposting to this issue queue in case others run into this issue (see https://github.com/auth0/angular2-jwt/issues/211)

**Comment by luisrudge** [comment]
Hi @stefanruijsenaars - the problem is that angular-router clears the hash (https://github.com/angular/angular/issues/6595) you're receiving from Auth0. We added the possibility to prevent Lock from parsing the hash when it is instantiated and resuming the authentication workflow in https://github.com/auth0/lock/pull/790. However, this was not released yet. There's a workaround you can use in the meantime: https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/issues/40#issuecomment-265170465.

With that being said, next version is scheduled to be released next week and we'll have angular examples you can follow.
Thanks!

**Comment by stefanruijsenaars** [comment]
thank you!
