### ISSUE TITLE
Spinner lasts too long on load

### ISSUE THREAD

**Issue by maxlapides** [auth0/lock#840]
Before Auth0 Lock was built with React, it loaded very fast. If I visit the Auth0 hosted version of the login page that still uses Auth0 Lock 9, it loads almost instantly. With Auth0 Lock 10, the loading process looks something like this:

1. Load app (~2 seconds)
2. Auth0 Lock appears with logo and spinner (~1.8 seconds)
3. Form fields or login with previous account button appears (user can now interact)

The initial load time is partly my problem, as we have yet to implement proper code splitting. I believe that Auth0 Lock is also partially responsible for this, as noted in https://github.com/auth0/lock/issues/113

The following ~1.8 seconds of spinner is my main concern. When I see this spinner, what am I waiting for? I see that there's an API call to `xyz.auth0.com/user/ssodata`, but we get a response from that endpoint in ~65ms. That API call is triggered at the same time as the spinner appears, but the spinner continues for an additional ~1735ms. This is a really long time to wait. Why is this happening? Is there anything that can be done to improve this?

**Comment by luisrudge** [comment]
Hi @maxlapides. Can you put a sample project somewhere we can test this with your client? Everything is loading super fast from me (I'm from Brazil) in [this website](https://auth0-repro-809.now.sh). Can you hit this website and compare the loading time with your application?
![screen shot 2017-02-01 at 13 42 20](https://cloud.githubusercontent.com/assets/941075/22513851/9a280a24-e884-11e6-9d9f-874a96fb0ea2.png)

**Comment by theopak** [comment]
<img width="1237" alt="screen shot 2017-02-01 at 11 38 45 pm" src="https://cloud.githubusercontent.com/assets/693878/22537314/a4790da4-e8d7-11e6-899e-661fa043ee13.png">

![xfnah5tdw2](https://cloud.githubusercontent.com/assets/693878/22537402/4a399f6a-e8d8-11e6-8529-e340dfcd3a48.gif)


@luisrudge cool test site! I share the same concern that @maxlapides explained, and when I used Chrome DevTools on https://auth0-repro-809.now.sh I measured an experience that's consistent with his numbers, and at the same time consistent with the network speeds that you have. 

You can see in my screenshot that network activity completes relatively quickly… but then there's ~1500ms between when Lock starts showing on the page and when it's finished animations and has input fields ready. Have I measured that correctly?

Does the amount of time used up by the loading spinner have anything to do with the amount of time that network requests use? Is there something else going on that takes up the extra time, such as JS parsing or execution or arbitrary delays?

Anyway, I'm glad someone's taking a look at this. It's frustrating for me that this is part of the first run experience for each of my users yet there doesn't seem to be anything I can optimize in my own code to address this part of the timeline.

**Comment by theopak** [comment]
This looks suspicious… https://github.com/auth0/lock/blob/0149fe9dd741a29e36f1191efed6fe4ebf8ca581/src/core/loading_screen.jsx#L23

```js
class LoadingPane extends React.Component {

  componentDidMount() {
    const { model } = this.props;
    pinLoadingPane(l.id(model));
    setTimeout(() => unpinLoadingPane(l.id(model)), 1200);
  }
```

Does that 1200ms constant timeout value exist because there's something else going on that tends to take almost that long? Or would fixing this issue be as simple as changing that value to a lower number?

**Comment by luisrudge** [comment]
Hi @theopak. Thanks for the time you took to help us with this issue. The code you mentioned is indeed one of the things to blame with this performance issue. We made a quick fix (#853) to reduce that forced waiting time. Unfortunately, we can't, as of now, remove this delay altogether because of some css animations that happen at the same time. We're discussing internally about only showing the loading animation if something is taking more than X ms, but this is an on going discussion. For the the time being, the best we can do right now is #853. Let me know how this works for you. Again, thanks for your help!

**Comment by dazaria** [comment]
@luisrudge thank you for making the change, and for the attention on this issue. Since the login page will be the first thing almost any user sees, reducing the time it takes for them to start entering their credentials is super critical for ensuring they have a good experience. Our users, in particular, often need to very quickly log in to our product to check something out, and every fraction of a second counts! Please keep us posted on further reductions in the "time to enter credentials" and particularly the reduction of the loading animation time.

**Comment by luisrudge** [comment]
@dazaria if you use the inline version (instead of the overlay), it doesn't trigger the same animations and the loading time will be almost instant. If you want to squeeze every ms, it's worth a shot 😊

**Comment by maxlapides** [comment]
@luisrudge thanks so much for the quick adjustment and the suggestion to use the inline version. i will give it a shot! my philosophy is animations should never slow down the user experience. if the user is forced to move slower because of an animation, that animation shouldn't be there :)

**Comment by maxlapides** [comment]
@glena @luisrudge I just tried out using the inline version instead of the overlay version. I had already disabled the initial loading animation with a handy `transition: none !important` so this change didn't make any difference for us.

I am appreciative that you were able to decrease the wait time from 1200ms to 500ms, but that wait time needs to be exactly the amount of time for the API call and no more than that. 500ms is much better than 1200ms, but it is still a huge amount of time. We _are_ trying to squeeze every ms because every ms does matter. I'll be following up on this over the following weeks because I do see this 500ms as a major problem.

**Comment by hzalaz** [comment]
@maxlapides if you need to squeeze everything building your own login box with auth0.js is the path to go since you will have complete control. 

This is even more important if you only perform username/password login and maybe a social login, Lock handles a lot of features, and configures itself from your client settings so some time should be consumed for that in favor of convenience.

**Comment by maxlapides** [comment]
@hzalaz Although all of that is true and fair, I think we're confusing issues here. I am talking specifically about the artificial 500ms wait time that still exists. I unfortunately don't have unlimited time to rewrite our login page, so I'm trying to tackle the largest bottlenecks first.

**Comment by hzalaz** [comment]
I know, but probably we made the decision to provide that initial transition of 500ms in Lock and avoid making sudden refreshes on load.

**Comment by maxlapides** [comment]
@hzalaz I don't understand. I think it is of critical importance that we remove this extraneous wait time. When do you think I can expect an update on this?

**Comment by hzalaz** [comment]
Sorry was in a hurry to get back home so I rushed my answer.

The decrease to 500ms will probably be in our release in 1 week, after we test it and see if we are ok with how the transition is from loading to loaded. I am not sure we are going to remove the delay entirely since we want to have that transition and 500ms is for us not a long time to wait (2 seconds was a long time). 
That was the reason I suggested auth0.js, also there is the fork route too, if you don't like our decision to have that transition animation of that duration.

**Comment by dazaria** [comment]
@hzalaz we tried the forked route before, but there were so many forced updates that the overhead in extra work required for us was too high.

We were excited to jump on the current version of lock, but are now very  disappointed in the performance hit that we took in doing so. Most developers these days building apps that allow users to interact with their content in less than a second; to deliberately have a .5 second delay just to enter credentials isn't great.

Is there a reason for the 500ms delay i.e. is it done intentionally in order to provide a certain set of functionality, or is it a deliberate delay just to add the animation?

It's very important to us to get users into our application as quickly as possible with minimal delay. I have to imagine that a number of other companies are in the same situation. Login is a necessary step, but also acts as a barrier to entry for important content and should be as simple, painless, and _fast_ as possible.

**Comment by hzalaz** [comment]
@dazaria to be honest this is the first time this issue has been raised (the delay in the loading animation) and that's why that long 2sec delay was not noticed before, we were more focused on the side of the library instead among other things. 
Not sure why this was never raised before, maybe some our clients either don't have the login box only as the first thing on the site or is not shown a lot since they keep longer sessions, maybe something else.

We wanted the animation & transition and that's the origin for the delay (I agree it was too long at first) and 500ms for us is not a long time for most use cases. 
There is room for improvements like avoiding loading the client load to see how lock should be configured (by specifying it in your code), preloading that info in your server and render the initial state of Lock, bundle the css in a separate file, or don't load css at all so there is no need for the loading screen but those things are just ideas we want to explore during this year alongside other requirements we have from the rest of our customers and improving lock codebase.

I know it might not be great but this is our vision of how the login box should look and behave and we will try to improve as far as we can  but eventually we can't please everyone and that's the reason we try hard to make it easy to build your own login box.

**Comment by maxlapides** [comment]
@hzalaz i still don't understand why you think this 500ms is necessary. could you please explain this?

the reason why i'm raising this issue now is because i just upgraded to Auth0 Lock 10. i'm sure others are in a similar position. just because others haven't spoken up doesn't mean it's not affecting them.

**Comment by hzalaz** [comment]
Because we wanted to show the loading indicator and animation, its true that someone can be in the same position but maybe they don't care or is fine enough for them. e.g. I know the size is an issue since mostly everyone says so otherwise we can only guess or just use our opinion.

I don't want to spend a lot arguing about this, we briefly tested with 500ms and seems to look good for us. If we can decrease it further while it still feels ok for us we'll do (and nothing breaks).

Thanks for the input guys

**Comment by theopak** [comment]
Hey, I see that https://github.com/auth0/lock/pull/853 has not been merged or released yet, so I'm not sure if this issue should be marked as closed. Does anyone have an ETA on https://github.com/auth0/lock/pull/853?

**Comment by hzalaz** [comment]
@theopak sometime this week or the next.

**Comment by maxlapides** [comment]
This may be helpful for resolving this issue: https://github.com/thejameskyle/react-loadable
