### ISSUE TITLE
Improve error handling when signup fails because of a Rule or login error

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#85]
It can be confusing to see a login error message when the user has signed up:

![1cz3zhbxh7](https://cloud.githubusercontent.com/assets/829698/5231767/cbbf8236-771d-11e4-9a5c-e77f2261f738.gif)

Maybe send the user back to the login screen or show a different error message?

**Comment by mgonto** [comment]
https://ask.auth0.com/t/custom-error-message-in-login-popup/436/3 Notify here

**Comment by eigilsagafos** [comment]
+1

**Comment by cristiandouce** [comment]
The fact that a sign in fails right after a signup is rare, since you already signed up with the same credentials and therefore you should be able to sign-in.

Unless the case where you have a rule and you validate some other external credentials to let users access your application.

So, yes... after an unsuccessful sign in from a successful signup, you should be displayed the `login` view with your email in place and the `custom rule` error message from auth0/lock#86

@rolodato @sandrinodimattia will you guys confirm this as the intended experience?
Thanks!

**Comment by cristiandouce** [comment]
OFC, if the error is a `User already exists` or something related to the signup, you should still see the signup view.

**Comment by hzalaz** [comment]
Already added in v9
