### ISSUE TITLE
Make `mustAcceptTerms` work on social logins

### ISSUE THREAD

**Issue by davidascher** [auth0/lock#903]
Currently, the `mustAcceptTerms` option is only available for users who use the username/password login, not for social logins.  This seems like a bug worth fixing.

Social logins are a great convenience for users, but many sites need the legal protection of the users accepting the ToS.  The current setup requires auth0 users to choose one or the other.

(This is discussed on the forums at https://auth0.com/forum/t/enforce-mustacceptterms-on-social-connections/4931 but I figure this repo is where the work will be done).

**Comment by hzalaz** [comment]
We'll try to see what we can do but it will not be a complete solution since the user can also signup from the login tab since both operations are the same and there is no ToS in login pane. (A workaround is to only show signup but you will still need a guard on login which is not possible now)

The feature is not useless since its meant for database connections since its part of the database options https://github.com/auth0/lock#database-options and some sites reword the ToS disclaimer to say that a user implicitly accepts them when they sign up so that might be a temp workaround now if acceptable. 

Will close this in favor of #919 to block the clicks in the sign up pane and add an item in our internal backlog for a solution for the sign up from the login tabs
