### ISSUE TITLE
`id_token` undefined if lock shown with custom auth options 

### ISSUE THREAD

**Issue by shusson** [auth0/lock#943]
Lock version (10.13.0)
 Browser & OS (Linux && chrome Version 57.0.2987.110 (64-bit))

If I show the lock with custom params e.g:
```
this.lock.show({
    auth: {
        params: {state: this.router.url},
    }
});
```
Then the authResult in the authenticated callback has an undefined `id_token`.

My original lock options look like:

```
const options: any = {
    auth: {
        redirectUrl: constants.ORIGIN_URL + 'initiatives',
        responseType: 'token'
    }
};
```

**Comment by luisrudge** [comment]
Hi. There's more info about this [here](https://github.com/auth0/lock/issues/859).
Since you're using the redirect mode, you can use `responseType: 'id_token token'` or `auth.params.scope: 'openid idToken'` to get the idToken.

In popup mode, the responseType alternative won't work, so you can only use the scope alternative. In your case, either case will work.

**Comment by luisrudge** [comment]
Actually.. I just found out the real issue here: [This line](https://github.com/auth0/lock/blob/42a484759251644ba0a3a375b5494307c89139dd/src/core/index.js#L202) gets `auth.params` from the `show` method or `auth.params` from the moment you instantiate lock. It's something like: `const useThisParams = paramsFromShowMethod || paramsFromLockCreation`. Since you're passing `auth: {params: {state: 'foobar'}}`, you're not getting the default scope that is added [here](https://github.com/auth0/lock/blob/42a484759251644ba0a3a375b5494307c89139dd/src/core/index.js#L257).
So, in your case, you just need to add `scope: 'openid'` to your `auth.params` object in the `show` method:

```js
this.lock.show({
    auth: {
        params: {state: this.router.url}, 
        scope: 'openid'
    }
});
```

I'll check internally at Auth0 if it makes sense to merge both objects or not so this doesn't happen again and will get back to this issue after that (tomorrow or Monday).

**Comment by shusson** [comment]
@luisrudge thanks for your reply. Is there any documentation that supports this? It sounds like it's a bug and we are just working around it.

**Comment by luisrudge** [comment]
Not a bug. You just have to be aware that, if you want to pass some auth params, you have no defaults anymore and we don't have this documented or even in the readme.

We're discussing making some changes to this options (basically remove scope from `auth.params` and putting it inside the `auth` object), but this is not a consensus internally yet. So, for the time being, we'll update docs to reflect the actual behavior.
