### ISSUE TITLE
Lock doesn't seem to be working with Inferno JS

### ISSUE THREAD

**Issue by woutersterp** [auth0/lock#965]
After reading this tutorial https://auth0.com/blog/learn-about-inferno-js-build-and-authenticate-an-app/. It seemed quite easy to integrate auth0 into an Inferno app. But after trying to get it working for a while, my app keeps spitting up errors of missing React.

```
Failed to compile.

Error in ./~/auth0-lock/lib/i18n.js
Module not found: Can't resolve 'react' in 'D:\...\node_modules\auth0-lock\lib'

 @ multi ./~/inferno-dev-utils/webpackHotDevClient.js ./~/inferno-scripts/config/polyfills.js ./~/inferno-dev-utils/crashOverlay.js ./src/index.js
```

Somehow it keeps on telling me React cannot be resolved. This seems logical, since I'm using Inferno, but in the tutorial this works. It seems now that Lock is incompatible with Inferno. 

Is there some workaround for this issue?

**Comment by luisrudge** [comment]
I pinged the post author about this issue.

**Comment by kmaida** [comment]
Hello @woutersterp! After a quick investigation into your issue, I'm unsure as to why you are receiving that particular error since the `auth0-lock` npm module should be implementation-independent. Are you attempting to integrate Auth0 into an existing Inferno app (not the app in the tutorial)?

I am planning to update the Inferno tutorial in full to the latest version of Inferno and the latest `create-inferno-app` in the next month or so. It's on backlog and has no estimated publish date at this time, as I'll be away at ng-conf 2017 this upcoming week and then have another post that is prioritized.

Was your project originally a React app that was later converted to Inferno?

**Comment by kmaida** [comment]
`auth0-lock` has React as a dependency and we suspect that Inferno could be interfering with this dependency by aliasing it. It's being investigated.

**Comment by woutersterp** [comment]
@kmaida Thanks for your reply! Sorry for my late response, I was not able to work on my Inferno project the last week. I'll try to fix the React-interfering problem, but I'm quite new to Inferno, so I can't promise anything. 

Is there some way I can keep updated on your progress around this issue? Do you have some kind of issue tracker I can subscribe on?

**Comment by kmaida** [comment]
@woutersterp Updates for this issue should be posted here or the issue will be closed when resolved. When it's resolved, the article will also be updated. :)

**Comment by kmaida** [comment]
Because of our new auth pipeline, the Inferno sample and article are being updated to use auth0.js instead of Lock. @luisrudge Doing so solves this issue because Lock is no longer used. This does remain an issue with Lock, but the advised pipeline no longer recommends hosting Lock locally so this may be a non-urgent issue. I'll close this issue shortly.

**Comment by kmaida** [comment]
@woutersterp and @luisrudge: This issue can now be closed (I don't have permissions to do so). The tutorial has been updated and now works (it no longer uses local Lock). @woutersterp, please check out the article again as there have been several changes made to the authentication section. https://auth0.com/blog/learn-about-inferno-js-build-and-authenticate-an-app/ Thanks!!

**Comment by luisrudge** [comment]
Thanks @kmaida
